### ISSUE TITLE
Selfhost fonts

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/tutorial#1]
Currently we get multiple fonts from `fonts.googleapis.com` which allows Google to track the users. Instead of downloading them, we should add them to the `fonts/` directory.

**Comment by theScrabi** [comment]
The problem is that the side folder is auto generated by using `mkdocs gh-deploy`. I'll try to override the current theme.

**Comment by theScrabi** [comment]
There seems to be a [way](http://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme), but for me the setup they talk about crashes.

**Comment by TobiGr** [comment]
I think they fixed [this](https://github.com/rtfd/sphinx_rtd_theme/commit/218e06f4ca933c44f2919d34ccd9ec30c6f472f8) in this commit, but it is from 2014. How can we check which version of the theme is installed?

**Comment by theScrabi** [comment]
I think it depends on which version of mkdocs you are using. However apparently we could self host the theme:
http://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme

I was not able to do that yet since my mkdocs installation crashes on self hosted themes.

**Comment by TobiGr** [comment]
It's strange, but the link to the theme repository is incorrect :D
https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes/readthedocs seems to be the right repository. We only have to override `base.html`. I have also problems to do this, but I'll try to figure it out. I guess we only need an extra `main.html` which extends the `base.html` and our modified `base.html`.

**Comment by theScrabi** [comment]
Thanks :D
